### ISSUE TITLE
{% load admin_static %} is deprecated in favor of {% load static %}

### ISSUE THREAD

**Issue by freezed** [barseghyanartur/django-fobi#213] opened 2019-04-23 07:59 UTC
My tests warns me about  `{% load admin_static %} ` deprecation.

This tag is used in  `simple` & `DjangoCMS` themes :
https://github.com/barseghyanartur/django-fobi/search?q=admin_static&type=Code

Was it removed from other themes, or it just had be only used here?

I replaced `admin_static` by `static` in my code : 
```
fobi/contrib/themes/simple/templates/simple/base_edit.html
fobi/contrib/themes/simple/templates/simple/dashboard.html
fobi/contrib/themes/simple/templates/simple/edit_form_entry.html
fobi/contrib/themes/simple/templates/simple/edit_form_wizard_entry.html
fobi/contrib/themes/simple/templates/simple/form_wizards_dashboard.html
fobi/contrib/themes/simple/templates/simple/import_form_entry.html
```
Without more tests or checks, and it looks like doing the job.

Can I just commit this change or it needs some other checks ?

(I run this in `Django` 2.1.7 & 2.2)

**Comment by barseghyanartur** [comment] 2019-04-23 08:04
@freezed:

Admin theme is theme which looks like Django admin. Other themes don't need that.

You could make simple checks in templates.

https://github.com/barseghyanartur/django-nine#in-templates

```html
{% if VERSIONS.DJANGO_GTE_2_1 %}
    {% load static %}
{% else %}
    {% load admin_static %}
{% endif %}
```

**Comment by freezed** [comment] 2019-04-23 13:30
I try conditional loading in template, but on one hand my test still fail :

* `settings.py` : https://gist.github.com/freezed/d5b18e8218c23fc64e4e8dc467e4b2a4
* `theme/simple` : https://github.com/freezed/django-fobi/commit/3ebfa83a30a47ce593d8c123fc248fff71b093e0?diff=split
* response : `.venv/lib/python3.6/site-packages/django/contrib/admin/templatetags/admin_static.py:14: RemovedInDjango30Warning: {% load admin_static %} is deprecated in favor of {% load static %}`

On the other hand, with the same basecode / settings, the use of `nine` in a basic template using a browser on `./manage.py runserver` works : 

* `template.html` : `<p>DJANGO_GTE_2_1: {{ VERSIONS.DJANGO_GTE_2_1|yesno:"yeah,no,maybe" }}</p>`
* response : `DJANGO_GTE_2_1: yeah`

Is there something I miss between `runserver` & `pytest` ?

**Comment by barseghyanartur** [comment] 2019-04-23 13:54
@freezed:

Did you push to your branch? I could take a look.

**Comment by 0pt1c** [comment] 2020-04-02 20:11
We are trying to update to django 3.0 and are getting errors from the templates for the deprecated import.

I made a comment over on the merged PR for this issue, but I wanted to post one here also since the issue is still open.

https://github.com/barseghyanartur/django-fobi/pull/214#issuecomment-608072628

**Comment by barseghyanartur** [comment] 2020-04-03 21:59
@0pt1c:

Done in 0.16.2.

**Closed by barseghyanartur** 2020-04-03 21:59 UTC
