### ISSUE TITLE
ProgrammingError on CSV/XLS export 

### ISSUE THREAD

**Issue by jeremytiki** [barseghyanartur/django-fobi#86] opened 2017-09-26 14:39 UTC
After setting up a basic fobi and saving a basic form and a few entries I attempted to export the data to csv/xls and recieved the following error:

![screen shot 2017-09-26 at 10 30 17 am](https://user-images.githubusercontent.com/1173792/30865941-f3960fb2-a2a5-11e7-9031-72dce0efcb44.png)

I'm using Python 3.5.1 and Django 1.10
```
$ pip freeze
certifi==2017.7.27.1
chardet==3.0.4
Django==1.11.5
django-autoslug==1.9.3
django-cleanup==1.0.1
django-cors-headers==2.1.0
django-filer==1.2.8
django-fobi==0.12.2
django-formtools==2.0
django-mptt==0.8.7
django-nine==0.1.13
django-nonefield==0.2
django-polymorphic==1.0.2
django-python3-ldap==0.11.0
easy-thumbnails==2.4.2
graphene==1.4.1
graphene-django==1.3
graphql-core==1.1
graphql-relay==0.4.5
idna==2.6
iso8601==0.1.12
ldap3==2.3
olefile==0.44
Pillow==4.2.1
promise==2.0.2
psycopg2==2.7.3.1
pyasn1==0.3.2
pytz==2017.2
requests==2.18.4
simplejson==3.11.1
singledispatch==3.4.0.3
six==1.11.0
typing==3.6.2
Unidecode==0.4.21
urllib3==1.22
vishap==0.1.5
```

**Comment by barseghyanartur** [comment] 2017-09-27 08:05
@jeremytiki:

I can't reproduce it. Could you paste the full trace?

**Comment by barseghyanartur** [comment] 2017-10-09 12:05
I'm closing this for now. Feel free to reopen any time (if problem still occurs).

**Closed by barseghyanartur** 2017-10-09 12:05 UTC
Labels: investigate
